### PR TITLE
Clean Build

### PR DESCRIPTION
**Pull request by bruceme**
Resolves issue with the not-yet-stable  vec.into_raw_parts() function use.  You really wanted to get the first byte of any pixel in a rust-safe way.  I think this does that.  I'm going to use your flightsim for a real flying EFIS project. This project was perfect, thanks!

### CODE REVIEW

**Comment by Kl4rry** [comment]
Cool seeing some one get a use out of this project. We are not really adding features to it anymore but I will happily look at PRs. Just say when you feel done with the PR and I have  a look at it.

**Comment by bruceme** [comment]
I'm done, let me know if it has anything you don't like/want.  I'm actively
developing in a different branch now.  I added fps, do you want that?

**Comment by bruceme** [comment]
[image: image.png]

**Comment by wiengman** [comment]
Fps sounds like a neat feature to have, but as previously mentioned we have no intention of developing on this project in the near future. But we are happy to look at PRs.

Changes looks good overall.

**Comment by bruceme** [comment]
you have the PR for FPS

**Pull request merged**
